# Generated by Django 4.2.1 on 2023-07-03 07:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="commented_at",
        ),
    ]
