# Generated by Django 4.2.1 on 2023-06-19 06:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="category",
            new_name="categories",
        ),
    ]
