# Generated by Django 4.2.1 on 2023-06-19 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_rename_category_listing_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="Watchlist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("listings", models.ManyToManyField(to="auctions.listing")),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="watchlist",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user",
                to="auctions.watchlist",
            ),
        ),
    ]
