# Generated by Django 4.2.1 on 2023-06-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_alter_listing_winner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="listing",
            name="starting_bid",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
