# Generated by Django 4.2.1 on 2023-06-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0006_alter_bid_amount_alter_listing_starting_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="image_url",
            field=models.URLField(null=True),
        ),
    ]
